### ISSUE TITLE
portaudio.com has no SSL certificate

### ISSUE THREAD

**Issue by Be-ing** [PortAudio/portaudio.github.io#2]
The domain should be set up with a free SSL certificate from [Let's Encrypt](https://letsencrypt.org/).
![image](https://user-images.githubusercontent.com/9455094/104224681-eeef5300-540a-11eb-9c87-52bedcca1035.png)

I think GitHub pages automatically sets up the site with Let's Encrypt.

**Comment by philburk** [comment]
Portaudio.com now uses SSL.

https://files.portaudio.com/
https://www.portaudio.com/
